version: "3"

services:

  mysql:
    image: mysql:latest
    container_name: mysql-qthttt
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: phpMyAdmin-qthttt
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1

  redis:
    container_name: redis-qthttt
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

networks:
  db-network:
    external: true
    driver: bridge